version: '3'
services:
  db:
    container_name: opinions
    image: mysql
    ports: 
      - 3307:3307   
    environment:
      MYSQL_DATABASE: opinions
      MYSQL_ROOT_PASSWORD: wsch8001
    volumes:
      - ./dbdata:/var/lib/mysql