server:
  port: 8000

spring:
 application:
   name: gateway
 cloud:
   gateway:
     routes:
       - id: accounts
         uri: lb://ACCOUNTS
         predicates:
           - Path=/accounts/**
       - id: opinions
         uri: lb://OPINIONS
         predicates:
           - Path=/opinions/**
       - id: aggregator
         uri: lb://AGGREGATOR
         predicates:
           - Path=/aggregator/**

eureka:
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8070/eureka/
  instance:
    hostname: host.docker.internal