server:
  port: 8071

spring:
 application:
   name: gateway
 cloud:
   gateway:
     routes:
       - id: accounts
         uri: lb://ACCOUNTS
         predicates:
           - Path=/accounts/**

eureka:
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost