server:
  port: 8082

spring:
  application:
    name: aggregator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:33064/aggregator
    username: root
    password: wsch8001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8070/eureka/
  instance:
    hostname: host.docker.internal