version: '3'
services:
  db:
    container_name: aggregator
    image: mysql
    ports: 
      - 33064:3306   
    environment:
      MYSQL_DATABASE: aggregator
      MYSQL_ROOT_PASSWORD: wsch8001
    volumes:
      - ./dbdata:/var/lib/mysql